### ISSUE TITLE
Delete Example Code should show how to use the "PhysicalResourceId"

### ISSUE THREAD

**Issue by ikben** [aws-cloudformation/aws-cloudformation-rpdk-python-plugin#61]
This is something that seems also wrong or unclear in the other examples of DeleteHandlers, so it might be an issue that's bigger than this repository.

If you follow the steps to implement the handlers, you might end up with something like this to manage an EC2 Key Pair (I'm skipping the not relevant parts of the code):

in the create handler:
```python
model = request.desiredResourceState
ec2 = session.client("ec2")  # type: botostubs.EC2
try:
    response = ec2.import_key_pair(
        KeyName=model.KeyName, PublicKeyMaterial=model.PublicKey
    )
except ClientError as e:
    if e.response.get("Code") == "InvalidKeyPair.Duplicate":
        raise exceptions.AlreadyExists(resource_type, model.KeyName)
    else:
        # raise the original exception
        raise
```
And in the delete handler:
```python
model = request.desiredResourceState
ec2 = session.client("ec2")  # type: botostubs.EC2
# DeleteKeyPair does not raise an exception if the KeyPair does not exist
ec2.delete_key_pair(KeyName=model.KeyName)
```

However, this leads to terrible results when you actually run into the case of an already existing keypair. What happens is:

- The create handler notices that the keypair already exists (👍 )
- CloudFormation fails and rolls back the stack
- CloudFormation calls the delete handler
- The DeleteHandler gets the KeyName of the already existing key, and deletes that (😧)

This is a serious issue and the RPDK and/or CloudFormation should do as much as possible to prevent people from writing code that behaves this way. I'm not sure what the solution is, but the way custom resources have an extra parameter with the physical resource id might help.

**Comment by ikben** [comment]
This might also be an issue with my schema? In any case, it is easy to make that mistake now

**Comment by tobywf** [comment]
depending on the underlying API, there's always a potential for handlers to accidentally adopt resources if the primary identifier can be specified by the user. from my understanding, an effective workaround would be e.g. to randomly identify the resource, and return that as a read-only property.

in effect, the handler creating a random ID and returning that should be the same thing as us generating a physical resource IDs, right? i think this is the reason we don't provide physical resource IDs, to give handler authors more freedom since different APIs may require IDs in formats other than the physical resource ID provided.

in any case, if you can get the ARN of a stack to us somehow where this happened, that could help the team understand what went on. i'm not sure what payload would be passed to the delete handler, since `AlreadyExists` shouldn't return a model. so this is a good shout out.

**Comment by ikben** [comment]
> depending on the underlying API, there's always a potential for handlers to accidentally adopt resources if the primary identifier can be specified by the user. from my understanding, an effective workaround would be e.g. to randomly identify the resource, and return that as a read-only property

In my opinion a failing create call should be able to prevent that.

> in effect, the handler creating a random ID and returning that should be the same thing as us generating a physical resource IDs, right?

Random would only work if you can save state somewhere. I'm trying to avoid that :).

> if i were to guess this is the reason we don't provide physical resource IDs, to give handler authors more freedom since different APIs may require IDs in formats other than the physical resource ID provided?
CloudFormation still shows us the physical resource id. if I understood it correctly this is created form the "primaryIdentifier" in the model, so I still have a lot of freedom about what I put there.

> in any case, if you can get the ARN of a stack to us somehow where this happened, that could help the team understand what went on. i'm not sure what payload would be passed to the delete handler, since AlreadyExists shouldn't return a model. so this is a good shout out.


There is apparently an error in the exception handling of the above code, so the actuall returned error was an "InternalFailure".  I think everything else still applies though. 
As you can see in this screenshot the console used "-" for the physical resource id of MyKeyPair. I think the delete should be a no-operation if that happens.

<img width="952" alt="Screenshot 2019-11-25 09 38 49" src="https://user-images.githubusercontent.com/1301221/69525002-7cea4f00-0f67-11ea-822e-1b911b498c1b.png">



StackArn: arn:aws:cloudformation:eu-west-1:277653584148:stack/keypair/2d351630-0efd-11ea-b7c9-0a259d6932f8

**Comment by ikben** [comment]
I'll wait on your analysis, I'm not ruling out me doing something wrong yet (however we should look at how to library can protect me against myself if that's the case).

I did take a quick look at the ses-resource-provider to see if I would have written other things if I started from that, but it has the exact same code in the DeleteHandler: https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-ses/blob/master/aws-ses-configurationset/src/main/java/software/amazon/ses/configurationset/DeleteHandler.java#L27

**Comment by rjlohan** [comment]
This doesn't look like a sequence of events which should occur and if it *is* happening like this then there's a bug somewhere.

What I would expect;

* The create handler notices that the keypair already exists (👍 )
* CloudFormation fails and rolls back the stack
* CloudFormation **does not** call the delete handler, because the CREATE action failed.

So either CloudFormation is incorrectly trying to delete a resource when CREATE failed, or your handler (or the library) is not correctly reporting failure to CloudFormation.

**Comment by tobywf** [comment]
in that stack, I don't see the delete handler getting called. did you get logs that it was called?

**Comment by ikben** [comment]
Oh, that's intersting. I assumed it would have been called because I didn't see the KeyPair in the console anymore.
However I do not see the call to DeleteKeyPair in CloudTrail.

I double checked, and the problem is that EC2 returns a very confusing error if you pass an invalid public key to ImportKeyPair. So I was doing things wrong.

I apologise for the confusion, It looks like CloudFormation did exactly what it should have done.

(it is a bit confusing that the Delete is still shown as an Event if there is nothing going to happen in the provider, but I assume this works the same for native resources).
